"""Shared data types for v8.0 architecture contracts."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal


Role = Literal["system", "user", "assistant", "tool"]
PatchStrategy = Literal["ast", "heuristic", "fallback"]
BudgetPriority = Literal["target", "related_symbols", "facts", "skeletons"]


@dataclass(slots=True)
class ChatMessage:
    """Represents one structured conversation message for model calls."""

    role: Role
    content: str


@dataclass(slots=True)
class PlanStep:
    """Describes one atomic edit step generated by the plan-first workflow."""

    order: int
    target_file: Path
    description: str


@dataclass(slots=True)
class EditPlan:
    """Structured edit plan that must be approved before execution."""

    thought: str
    steps: list[PlanStep]
    dependencies: dict[Path, list[Path]] = field(default_factory=dict)


@dataclass(slots=True)
class SymbolSlice:
    """Token-budgetable symbol unit used for granular eviction."""

    symbol_id: str
    file_path: Path
    content: str
    token_cost: int
    priority: BudgetPriority
    score: float = 0.0


@dataclass(slots=True)
class ContextBundle:
    """Assembled context payload for Gemini request execution."""

    total_tokens: int
    system_prompt: str
    target_context: list[SymbolSlice] = field(default_factory=list)
    related_symbols: list[SymbolSlice] = field(default_factory=list)
    facts: list[str] = field(default_factory=list)
    skeletons: list[str] = field(default_factory=list)


@dataclass(slots=True)
class FilePatch:
    """Single-file patch unit with ordered strategy metadata."""

    file_path: Path
    original: str
    updated: str
    strategy: PatchStrategy


@dataclass(slots=True)
class PatchTransaction:
    """Multi-file transaction payload for all-or-nothing patch apply."""

    patches: list[FilePatch]
    backup_dir: Path
    correlation_id: str


@dataclass(slots=True)
class ValidationResult:
    """Aggregate validation status after staged patch application."""

    ok: bool
    errors: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ModelResponse:
    """Structured model output with raw payload for auditing."""

    content: str
    raw: dict[str, Any] = field(default_factory=dict)
    usage: dict[str, int] = field(default_factory=dict)
