"""Project scanner package for skeleton and symbol table generation."""

from __future__ import annotations

from pathlib import Path

from .scan_project import scan_project
from .types import ScanArtifacts
from .write_outputs import write_scan_outputs

# INFO: 이전 단일 파일 클래스 계약:
# INFO: class FileScanner:
# INFO:     def __init__(self, project_root: Path) -> None: ...
# INFO:     def scan_project(self) -> ScanArtifacts: ...
# INFO:     def write_outputs(self, artifacts: ScanArtifacts) -> None: ...
# INFO:     def _iter_python_files(self) -> list[Path]: ...
# INFO:     def _is_ignored(self, path: Path) -> bool: ...
# INFO:     def _load_gitignore_patterns(self) -> list[str]: ...
# INFO:     def _matches_directory_ignore(self, rel_root: str, dirname: str) -> bool: ...
# INFO:     def _extract_skeleton(self, module: ast.Module) -> str: ...
# INFO:     def _render_class_skeleton(self, node: ast.ClassDef) -> list[str]: ...
# INFO:     def _render_function_skeleton(self, node, indent: int) -> list[str]: ...
# INFO:     def _build_signature(self, node) -> str: ...
# INFO:     def _render_arg(self, arg: ast.arg) -> str: ...
# INFO:     def _extract_symbols(self, module: ast.Module, rel_path: str) -> list[dict]: ...
# INFO:     def _symbol_entry(self, node, rel_path, parent, symbol_type) -> dict: ...
# INFO:     def _extract_calls(self, node: ast.AST) -> set[str]: ...
# INFO:     def _populate_used_by(self, symbols: list[dict]) -> None: ...
# INFO:     def _sha256_of_file(self, path: Path) -> str: ...
# INFO: 현재는 file_scanner/ 서브패키지 + scan_project / write_scan_outputs 함수로 전환됨.


class FileScanner:
    """Thin facade delegating to scan_project and write_scan_outputs (하위 호환용)."""

    def __init__(self, project_root: Path) -> None:
        self.project_root = project_root

    def scan_project(self) -> ScanArtifacts:
        return scan_project(self.project_root)

    def write_outputs(self, artifacts: ScanArtifacts) -> None:
        write_scan_outputs(self.project_root, artifacts)


__all__ = [
    "ScanArtifacts",
    "FileScanner",
    "scan_project",
    "write_scan_outputs",
]
